### ISSUE TITLE
Potential typo in Docs

### ISSUE THREAD

**Issue by lucasmccomb** [grommet/grommet-standalone#1]
When I was trying to get Grommet working in my existing React app, I found that I needed to include the `.scss` file suffix in `import 'grommet/scss/vanilla/index';`.

My import statement reads `import 'grommet/scss/vanilla/index.scss';`. 

Not sure if that's a typo or if there's something in babel that doesn't require file name suffixes (our app is using webpack), but figured it might be worth mentioning. Screen shot of whereabouts in docs below:

> ![image](https://cloud.githubusercontent.com/assets/5007314/19368608/cd6a0f58-916e-11e6-93ca-3a14a2724965.png)

Absolutely love Grommet. Thanks!

**Comment by alansouzati** [comment]
Thanks for bringing this up and for the kind words about Grommet 👍 . 

Webpack has the `extensions` entry in their config that allows you to remove the suffix for file paths: https://github.com/webpack/docs/wiki/Configuration#resolveextensions

I'm assuming you are missing this entry in your config:

```
  resolve: {
        extensions: ['', '.js', '.scss', '.css']
    },
```

You can either add the extensions in all files, or use resolve.extensions entry, it is up to you.

**Comment by lucasmccomb** [comment]
@alansouzati :facepalm: I'm very new to webpack - thanks for the help and apologies for creating an issue for that.

**Comment by alansouzati** [comment]
No need to apologize. It is good that search indexes will get this page available for folks that will eventually face a similar issue. 👍
