### ISSUE TITLE
ERROR in ./~/grommet/components/icons/base/More.js babel-runtime

### ISSUE THREAD

**Issue by evladik** [grommet/grommet-standalone#3]
Just cloned it and followed the instructions:
...
`ERROR in ./~/grommet/components/icons/base/Close.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/createClass' in D:\node\grommet-standalone\node_modules\grommet\components\icons
 @ ./~/grommet/components/icons/base/Close.js 27:20-64`
....

D:\node\grommet-standalone>npm ls -dev -depth 0
grommet-standalone@0.1.0 D:\node\grommet-standalone
├── babel-core@6.22.1
├── babel-loader@6.2.10
├── babel-preset-es2015@6.22.0
├── babel-preset-react@6.22.0
├── css-loader@0.23.1
├── node-sass@3.13.1
├── sass-loader@4.1.1
├── style-loader@0.13.1
└── webpack@1.14.0

**Comment by alansouzati** [comment]
added in https://github.com/grommet/grommet-standalone/commit/3e0deb66888854f6958edd66b2e20da4266872bd
