### ISSUE TITLE
Don't force sass loader to allow using grommet #1210

### ISSUE THREAD

**Issue by shai32** [grommet/grommet-standalone#5]
I think that forcing importing a sass file is a wrong approach
import 'grommet/scss/vanilla/index';

as we know create-react-app is very popular but we can't use it with grommet

we can solve it easily by adding a compiled css into grommet package
so we can just import a simple vanila css.

Thats good not only for create-react-app but also for anyone that don't want to add sass loader
only for using grommet.

Thats one limitation we can just remove

**Comment by ugurcemozturk** [comment]
This article solved my problem, check this out : [https://medium.com/@luce.williamt/using-grommet-with-create-react-app-8e8ddaa836ee#.17fk1ypyt](url)
@shai32 #Please inform me if your problem solved or not.

**Comment by tracybarmore** [comment]
Closing with grommet/grommet#1210 closure.
Also, a fun read: https://github.com/facebookincubator/create-react-app/issues/1639
